# Generated by Django 4.0 on 2021-12-25 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News_Portal', '0002_rename_author_name_author_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
